# Generated by Django 5.0.6 on 2024-06-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_subscribed",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Подписка актив"
            ),
        ),
    ]
